name: Lint

on: [push]

jobs:
  lint:
    runs-on: self-hosted
    container:
      image: ghcr.io/catthehacker/ubuntu:act-latest@sha256:148374205122af210a8ca475111dd1a2934a10bbeea39b53850041517dccc570

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: https://github.com/cachix/install-nix-action@630ae543ea3a38a9a4166f03376c02c50f408342 # v31.11.0

      - name: Lint
        run: nix flake check . -L --no-update-lock-file
