name: Lint

on: [push]

jobs:
  lint:
    runs-on: self-hosted
    container:
      image: ghcr.io/catthehacker/ubuntu:act-latest@sha256:2f22a801c486881e278401813586faf73fac7dd1d016cbe9e01122ef14a57850

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: https://github.com/cachix/install-nix-action@8aa03977d8d733052d78f4e008a241fd1dbf36b3 # v31.10.6

      - name: Lint
        run: nix flake check . -L --no-update-lock-file
