name: Lint

on: [push]

jobs:
  lint:
    runs-on: self-hosted
    container:
      image: ghcr.io/catthehacker/ubuntu:act-latest@sha256:b302f465fc3a466e5e222808edd59997842544853102fda7766147e998bbdc02

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: https://github.com/cachix/install-nix-action@8aa03977d8d733052d78f4e008a241fd1dbf36b3 # v31.10.6

      - name: Lint
        run: nix flake check . -L --no-update-lock-file
