{
  imports = [
    ./cmp.nix
    ./cord.nix
    ./flash.nix
    ./treesj.nix
    ./crates.nix
    ./treesitter
    ./conform.nix
    ./no-conf.nix
    ./orgmode.nix
    ./harpoon.nix
    ./gitsigns.nix
    ./wakatime.nix
    ./neo-tree.nix
    ./autopairs.nix
    ./telescope.nix
    ./colorizer.nix
    ./lightline.nix
    ./mini-align.nix
    ./rustaceanvim.nix
    ./mini-surround.nix
  ];
}
